runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
 
- url: /css
  static_dir: css
- url: /img 
  static_dir: img 
  
- url: /templates
  static_dir: html
  
- url: /img
  static_dir: img

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest