runtime: python27
api_version: 1
threadsafe: true

handlers:
<<<<<<< HEAD
 
- url: /css
  static_dir: css
- url: /img 
  static_dir: img 
=======
- url: /css
  static_dir: css
>>>>>>> d55dc03f58415e538b9e0d89974f28963fe6f656
  
- url: /templates
  static_dir: html
  
- url: /img
  static_dir: img

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest